import Head from 'next/head'
import { useRouter } from 'next/router';
import { useQuery } from '@apollo/client';

import { gql } from '../../generated-gq/gql';
import styles from '../../styles/Home.module.css'
import Application from '../../component/Application'

const APP_QUERY = gql(/* GraphQL */ `
    query ApplicationPage($id: ID) {
        application(id: $id ) {
            id
            name
        }
    }
`);

export default function ApplicatonPage() {
    const router = useRouter();
    const id = router.query.id?.toString();
    if (!id) {
        return '';
    }

    const { data, loading, error } = useQuery(APP_QUERY, { variables: { id } });
    return (
        <div className={styles.container}>
            <Head>
                <title>Applications!</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            { loading && 'Loading...' }
            {
                data && data.application && <h1>{data.application.name}</h1>
            }
            {
                data && data.application
                ? <Application applicationId={data.application.id} />
                : 'Not found'
            }
        </div>
    )
}
