import Head from 'next/head'
import { useQuery } from '@apollo/client';

import { gql } from '../generated-gq/gql';
import styles from '../styles/Home.module.css'
import Loading from '../component/Loading'

const ENV_QUERY = gql(/* GraphQL */ `
    query Enviroment {
        environments(p: "") {
            id
            name
            rules {
                key {
                    name
                }
                value
            }
        }
    }
`);

export default function Home() {
    const { data, loading, error } = useQuery(ENV_QUERY, {});
    return (
        <div className={styles.container}>
            <Head>
                <title>Applications</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Enviroments</h1>
            <Loading inProgress={loading} />
        </div>
    )
}
