import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { gql, useQuery } from '@apollo/client';

const QUERY = gql`
query {
    environments(p: "1") {
        id
        name
    }
    applications{
        name
        versions {
          version
        }
    }
}
 `;

export default function Home() {
    const { data, loading, error } = useQuery(QUERY);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App1</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Hello</h1>
            <pre>
                { JSON.stringify(data, null, 4) }
            </pre>
        </div>
    )
}
