import Head from 'next/head'
import { useQuery } from '@apollo/client';

import { gql } from '../generated-gq/gql';
import styles from '../styles/Home.module.css'
import Application from '../component/Application'

const APP_QUERY = gql(/* GraphQL */ `
    query ApplicationsList {
        applications {
            name
            versions {
                version
            }
        }
    }
`);

export default function Home() {
    const { data, loading, error } = useQuery(APP_QUERY, {});
    return (
        <div className={styles.container}>
            <Head>
                <title>Applications</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>All applications</h1>
            {
                data?.applications?.map(app => <Application application={app} />)
            }
        </div>
    )
}
