import Head from 'next/head'
import { useQuery } from '@apollo/client'
import Link from 'next/link'

import { gql } from '../generated-gq/gql'
import styles from '../styles/Home.module.css'
import Loading from '../component/Loading'

const APP_QUERY = gql(/* GraphQL */ `
    query ApplicationsList {
        applications {
            id
            name
            versions {
                version
            }
        }
    }
`);

function gratPathToApp(app: { id: string }) {
    return '/application/' + app.id;
}

export default function Home() {
    const { data, loading, error } = useQuery(APP_QUERY, {});
    return (
        <div className={styles.container}>
            <Head>
                <title>Applications</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>All applications</h1>
            <Loading inProgress={loading} />
            {
                data?.applications?.map(app => <div><Link href={gratPathToApp(app)}>[{app.id}] - {app.name}</Link></div>)
            }
        </div>
    )
}
